DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Controllers/AnchoragationController.cs
using DataAccessLayer;
using DataAccessLayer.Entities;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Collections.Generic;

namespace DepartmentWebApplication.Controllers
{
    public class AnchoragationController : Controller
    {
        private DepartmentEntities db = new DepartmentEntities();
        // GET: Anchoragation
        public ActionResult Index()
        {
            //выбрать планы, у которых у дисциплин .DepartmentId != null

            List<Plan> plans = db.Plans
                 .Include(p => p.Disciplines
                         .Select(d => d.Subject))
                 .Include(p => p.Speciality)
                 .ToList();


            foreach (Plan plan in plans)
            {
                var list = plan.Disciplines.ToList();
                list.RemoveAll(dis => dis.DepartmentId != null);
                plan.Disciplines = list;
            }

            ViewBag.Plans = plans;

            ViewBag.Faculties = db.Faculties
                .Include(f => f.Departments
                .Select(dep => dep.Disciplines));

            return View();
        }


        // POSt: Anchoragation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Anchorage(string[] departments, string[] disciplines)
        {
            SetDepartmentIdToDistributedDisciplines(departments);
            SetUnanchoragedDisciplines(disciplines);
            return RedirectToAction("Index", "Disciplines");
        }

        private void SetDepartmentIdToDistributedDisciplines(string[] departments)
        {
            Department department = null;
            for (int i = 0; i < departments.Length; i++)
            {
                int id = Convert.ToInt32(departments[i].Split('/')[0]);
                using (var database = new DepartmentEntities())
                {
                    if (id < 0)
                    {
                        department = database.Departments
                            .Include(d => d.Disciplines)
                            .FirstOrDefault(d => d.Id == -id);
                    }
                    else
                    {
                        if (department != null)
                        {
                            Discipline discipline = database.Disciplines.Find(id);
                            discipline.DepartmentId = department.Id;
                            database.SaveChanges();
                        }
                    }
                }
            }
        }

        private void SetUnanchoragedDisciplines(string[] disciplines)
        {
            if (disciplines == null)
            {
                return;
            }
            for (int i = 0; i < disciplines.Length; i++)
            {
                int id = Convert.ToInt32(disciplines[i].Split('/')[0]);
                using (var database = new DepartmentEntities())
                {
                    Discipline discipline = database.Disciplines.Find(id);
                    discipline.DepartmentId = null;
                    database.SaveChanges();
                }
            }
        }
    }




}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Anchoragation/Index.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Styles{
    <script src="~/Scripts/anchoragation_script.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js " integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj " crossorigin="anonymous "></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js " integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns " crossorigin="anonymous "></script>
    <script src="https://kit.fontawesome.com/3eb25f24fe.js" crossorigin="anonymous"></script>
}


@section Content{
    <div class="w-75 mx-auto border p-3 m-3">
        @using (Html.BeginForm("anchorage", "Anchoragation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h2 class="text-center">Закрепление дисциплины по кафедрам</h2>

                <div class="main d-flex justify-content-center">
                    <div class="d-flex justify-content-center">
                        <div>
                            <h4 class="text-center">Дисциплины</h4>
                            <select onclick="clearErrorMessage()" id="Disciplines" name="Disciplines" multiple size="10">
                                @foreach (var plan in ViewBag.Plans)
                                {
                                    <optgroup id="p_@plan.Id" label="@(plan.Speciality.NameAbbreviated + " " + plan.RegNumber)">
                                        @foreach (var discipline in plan.Disciplines)
                                        {
                                            <option value="@discipline.Id/@plan.Id">@discipline.Subject.Name</option>
                                        }
                                    </optgroup>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="button-container mx-3 mt-5 form-group">
                        <span class="btn btn-light border rounded px-5 py-2" onclick="moveDiscipline()"><i class="fas fa-arrow-right"></i> </span>
                        <br />
                        <span class="btn btn-light border rounded  px-5 py-2 " onclick="moveDisciplineBack()"><i class="fas fa-arrow-left"></i> </span>
                    </div>
                    <div>
                        <h4>Кафедры</h4>
                        <select onclick="clearErrorMessage()" id="Departments" name="Departments" multiple size="10">
                            @foreach (var faculty in ViewBag.Faculties)
                            {
                                <optgroup label="@(faculty.Name+" факультет")">
                                    @foreach (var department in faculty.Departments)
                                    {
                                        <option value="-@department.Id">@department.Name</option>
                                        foreach (var discipline in department.Disciplines)
                                        {
                                            <option value="@discipline.Id/@discipline.PlanId">--@discipline.Subject.Name</option>
                                        }
                                    }
                                </optgroup>
                            }
                        </select>
                    </div>
                </div>
                <p id="error-message" class="text-danger text-center my-2 d-none">Выберите кафедру</p>
                <div class="d-flex justify-content-center py-3">
                    <div class="mx-auto">
                        <input type="submit" value="Сохранить" class="btn btn-link border rounded mx-1" onclick="setSelected()" />
                    </div>
                </div>
            </div>
        }}