DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DepartmentWebApplication;
using DataAccessLayer.Entities;
using DepartmentWebApplication.Models;
using System.Reflection;
using DataAccessLayer;

namespace DepartmentWebApplication.Controllers
{
    public class PlanController : Controller
    {
        DataBaseDepartment db = new DataBaseDepartment();
        // GET: Plan
        public ActionResult Index()
        {
            return View(db.Plans.GetAll());
        }

        // GET: Plan/details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.GetItem((int)id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // POST: Plan/details/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int id, params int[] semesters)
        {
            using (var db = new DepartmentEntities())
            {
                List<Semester> list = db.Semesters.Where(s => s.PlanId == id).ToList();
                db.Semesters.RemoveRange(list);

                for (int i = 0; i < semesters.Length; i++)
                {
                    db.Semesters.Add(new Semester()
                    {
                        Number = i + 1,
                        Duration = semesters[i],
                        PlanId = id
                    });
                }
                db.SaveChanges();
            }
            return Redirect("/Plan/Details/" + id);
        }


        // GET: Plan/Create
        public ActionResult Create()
        {
            Plan plan = new Plan();
            plan.Date = DateTime.Now;
            return View(plan);
        }



        //// POST: Plan/Create
        //// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        //// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //// [ValidateAntiForgeryToken]
        //public ActionResult Create(Models.Plan plan)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Plans.Add(mapper.mapFromModel(plan));
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(plan);
        //}


        // POST: Plan/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Speciality,Speciality.Name,Speciality.NameAbbreviated,Specialization,Cipher,Duration,Date,RegNumber,Stage,FormStudy,Budget")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                int specialityId = db.Specialities.GetAll().Find(e => e.Cipher == plan.Speciality.Cipher)?.Id ?? -1;
                if (specialityId == -1)
                {
                    specialityId = db.Specialities.AddGetId(plan.Speciality);
                }

                plan.Speciality = null; // убирает второе добавление специальности в бд
                plan.SpecialityId = specialityId;
                db.Plans.Add(plan);
                return RedirectToAction("Index");
            }

            return View(plan);
        }

        // GET: Plan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.GetItem((int)id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            ViewData["SpecialityId"] = new SelectList(db.Specialities.GetAll(), "Id", "Name", plan.SpecialityId);
            return View(plan);
        }

        // POST: Plan/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SpecialityId,Specialization,Duration,Date,RegNumber,Stage,FormStudy,Budget")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                db.Plans.Edit(plan.Id, plan);
                //  db.Entry(mapper.Convert(planModel)).State = EntityState.Modified;
                //  db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(plan);
        }

        // GET: Plan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.GetItem((int)id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // POST: Plan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Plans.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer;
using DataAccessLayer.Entities;
using DepartmentWebApplication.Models;

namespace DepartmentWebApplication.Controllers
{
    public class SubjectsController : Controller
    {
        private DepartmentEntities db = new DepartmentEntities();
        private DataBaseDepartment db1 = new DataBaseDepartment();

        // GET: Disciplines
        public ActionResult Index()
        {
            var disciplines = db.Subjects;
            return View(disciplines.ToList());
        }

        // GET: Disciplines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject discipline = db.Subjects.Find(id);
            if (discipline == null)
            {
                return HttpNotFound();
            }
            return View(discipline);
        }

        // GET: Disciplines/Create
        public ActionResult Create()
        {
            ViewBag.PlanId = new SelectList(db.Plans.Include(e => e.Speciality), "Id", "Speciality.Name");
            Discipline ds = new Discipline();
            ds.Subject = new Subject();
            return View(ds);
        }

        // POST: Disciplines/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Discipline,Discipline.PlanId,Discipline.SequentialNumber,Discipline.Name" +
        //    ",Discipline.NameAbbreviated,Number,Exams,Credits,CourseProjects,CourseWorks,Lectures,Labs,Practices,Seminars,Audits" +
        //    ",Independents,Ksr")] DisciplineSemester disciplineSemester)
        //{
        //    int planId = disciplineSemester.Discipline.PlanId;
        //    if (ModelState.IsValid)
        //    {
        //        int disciplineId = db1.Disciplines.GetAll().Find(d => d.PlanId == planId
        //        && d.Name == disciplineSemester.Discipline.Name)?.Id ?? -1;
        //        if (disciplineId == -1)
        //        {
        //            disciplineId = db1.Disciplines.AddGetId(disciplineSemester.Discipline);
        //        }
        //        disciplineSemester.Discipline = null; //убирает второе добавление

        //        disciplineSemester.DisciplineId = disciplineId;
        //        db1.DisciplineSemesters.Add(disciplineSemester);
        //        return Redirect("/plan/details/" + planId);
        //    }

        //    return View(disciplineSemester);
        //}

        // GET: Disciplines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject discipline = db.Subjects.Find(id);
            if (discipline == null)
            {
                return HttpNotFound();
            }
            //ViewBag.PlanId = new SelectList(db.Plans.Include(e => e.Speciality), "Id", "Speciality.Name", discipline.PlanId);
            return View(discipline);
        }

        // POST: Disciplines/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PlanId,SequentialNumber,Name,NameAbbreviated,Exams,Credits,CourseProjects,CourseWorks,Lectures,Labs,Practices,Seminars,Audits,Independents,Ksr")] Subject discipline)
        {
            if (ModelState.IsValid)
            {
                db.Entry(discipline).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.PlanId = new SelectList(db.Plans.Include(e => e.Speciality), "Id", "Speciality.Name", discipline.PlanId);
            return View(discipline);
        }

        // GET: Disciplines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject discipline = db.Subjects.Find(id);
            if (discipline == null)
            {
                return HttpNotFound();
            }
            return View(discipline);
        }

        // POST: Disciplines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject discipline = db.Subjects.Find(id);
            db.Subjects.Remove(discipline);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Subjects/Create.cshtml
@model DataAccessLayer.Entities.Subject
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/Styles/Discipline/discipline_create_form.css")">
}


@section Content{
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "discipline-create-form" }))
    {
        @Html.AntiForgeryToken()

        <h4 class="discipline-create-form__title">Дисциплина</h4>
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PlanId, "План", htmlAttributes: new { @class = "discipline-create-form__label" })
                <div>
                    @Html.DropDownList("Discipline.PlanId", ViewBag.PlanId as SelectList, htmlAttributes: new { @class = "discipline-create-form__input" })
                    @Html.ValidationMessageFor(model => model.PlanId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SemesterNumber, htmlAttributes: new { @class = "discipline-create-form__label" })
                <div>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.SemesterNumber, "План", htmlAttributes: new { @class = "discipline-create-form__label" });*@


        @*#line default
            #line hidden

            #line 12 "D:\asp.net\rep\departmentwebapp\DepartmentWebApplication\DepartmentWebApplication\DepartmentWebApplication\Views\Disciplines\Create.cshtml"
                                __o = Html.DropDownList("Discipline.PlanId", ViewBag.PlanId as SelectList, htmlAttributes: new { @class = "discipline-create-form__input" });


            #line default
            #line hidden

            #line 13 "D:\asp.net\rep\departmentwebapp\DepartmentWebApplication\DepartmentWebApplication\DepartmentWebApplication\Views\Disciplines\Create.cshtml"
                                __o = Html.ValidationMessageFor(model => model.Discipline.PlanId, "", new { @class = "text-danger" });


            #line default
            #line hidden

            #line 14 "D:\asp.net\rep\departmentwebapp\DepartmentWebApplication\DepartmentWebApplication\DepartmentWebApplication\Views\Disciplines\Create.cshtml"




            #line default
            #line hidden

            #line 15 "D:\asp.net\rep\departmentwebapp\DepartmentWebApplication\DepartmentWebApplication\DepartmentWebApplication\Views\Disciplines\Create.cshtml"
                                __o = Html.LabelFor(model => model.SemesterNumber, htmlAttributes: new { @class = "discipline-create-form__label" });


            #line default
            #line hidden

            #line 16 "D:\asp.net\rep\departmentwebapp\DepartmentWebApplication\DepartmentWebApplication\DepartmentWebApplication\Views\Disciplines\Create.cshtml"
                                __o = Html.EditorFor(model => model.SemesterNumber, new { htmlAttributes = new { @class = "discipline-create-form__input" } });


            #line default
            #line hidden

            #line 17 "D:\asp.net\rep\departmentwebapp\DepartmentWebApplication\DepartmentWebApplication\DepartmentWebApplication\Views\Disciplines\Create.cshtml"
                                __o = Html.ValidationMessageFor(model => model.SemesterNumber, "", new { @class = "text-danger" })
                            </div>
                        </div*@

@*<div class="form-group">
        @Html.LabelFor(model => model.Discipline.SequentialNumber, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Discipline.SequentialNumber, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Discipline.SequentialNumber, "", new { @class = "text-danger" })
        </div>
    </div>*@

<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "discipline-create-form__label" })
    <div>
        @Html.EditorFor(model => model.Name, new
        {
            htmlAttributes = new
            {
                @class = "discipline-create-form__input",
       @onchange = "WriteAbbreviation(Discipline_NameAbbreviated, this.value)"
            }
        })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.NameAbbreviated, htmlAttributes: new { @class = "discipline-create-form__label" })
    <div>
        @Html.EditorFor(model => model.NameAbbreviated, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
        @Html.ValidationMessageFor(model => model.NameAbbreviated, "", new { @class = "text-danger" })
    </div>
</div>

@*<div class="form-group">
        @Html.LabelFor(model => model.Control, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EnumDropDownListFor(model => model.Control, null, htmlAttributes: new { @class = "discipline-create-form__input" })
            @Html.ValidationMessageFor(model => model.Control, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseType, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EnumDropDownListFor(model => model.CourseType, null, htmlAttributes: new { @class = "discipline-create-form__input" })
            @Html.ValidationMessageFor(model => model.CourseType, "", new { @class = "text-danger" })
        </div>
    </div>*@

@*<div class="form-group">
        @Html.LabelFor(model => model.Lectures, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Lectures, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Lectures, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Labs, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Labs, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Labs, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Practices, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Practices, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Practices, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Seminars, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Seminars, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Seminars, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Independents, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Independents, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Independents, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ksr, htmlAttributes: new { @class = "discipline-create-form__label" })
        <div>
            @Html.EditorFor(model => model.Ksr, new { htmlAttributes = new { @class = "discipline-create-form__input" } })
            @Html.ValidationMessageFor(model => model.Ksr, "", new { @class = "text-danger" })
        </div>
    </div>*@

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Добавить дисциплину" class="custom-btn" />
    </div>
</div>
}

    <div>
        @Html.ActionLink("Back to List", "Index", "Plan")
    </div>
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Subjects/Delete.cshtml
@model DataAccessLayer.Entities.Discipline

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Discipline</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Plan.Speciality)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Plan.Speciality)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SequentialNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SequentialNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.NameAbbreviated)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NameAbbreviated)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Control)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Control)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CourseType)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CourseType)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Lectures)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Lectures)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Labs)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Labs)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Practices)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Practices)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Seminars)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Seminars)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Audits)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Audits)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Independents)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Independents)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ksr)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ksr)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Subjects/Details.cshtml
@model DataAccessLayer.Entities.Discipline

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Discipline</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Plan.Speciality)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Plan.Speciality)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SequentialNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SequentialNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.NameAbbreviated)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NameAbbreviated)
            </dd>
    
            @*<dt>
                @Html.DisplayNameFor(model => model.Control)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Control)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CourseType)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CourseType)
            </dd>*@
    
            <dt>
                @Html.DisplayNameFor(model => model.Lectures)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Lectures)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Labs)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Labs)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Practices)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Practices)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Seminars)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Seminars)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Audits)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Audits)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Independents)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Independents)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ksr)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ksr)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Subjects/Index.cshtml
@model IEnumerable<DataAccessLayer.Entities.Subject>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Plan.Speciality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SequentialNumber)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameAbbreviated)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Lectures)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Labs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Practices)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seminars)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Audits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Independents)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ksr)
            </th>
            <th>
                Кафедра
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Plan.Speciality.NameAbbreviated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SequentialNumber)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameAbbreviated)
                </td>
        
                <td>
                    @Html.DisplayFor(modelItem => item.Lectures)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Labs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Practices)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seminars)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Audits)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Independents)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ksr)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Department.Name)
                </td>*@
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>