DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Controllers/DisciplinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer;
using DataAccessLayer.Entities;

namespace DepartmentWebApplication.Controllers
{
    //теперь назывется Disciplines
    public class DisciplinesController : Controller
    {
        private DepartmentEntities db = new DepartmentEntities();

        private List<string> DiplomaDisciplines = new List<string> {
            "Преддипломная практика",
            "Председатель ГЭК",
            "Члены ГЭК",
            "Нормаконтроль",
            "Утверждение",
            "Рецензирование"
        };

        // GET: DisciplineSemesters
        public ActionResult Index()
        {
            var disciplineSemesters = db.Disciplines
                .Include(d => d.Subject)
                .Include(d => d.Department)
                .Include(d => d.Plan.Speciality);

            return View(disciplineSemesters.ToList());
        }

        // GET: DisciplineSemesters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discipline disciplineSemester = db.Disciplines.Find(id);
            if (disciplineSemester == null)
            {
                return HttpNotFound();
            }
            return View(disciplineSemester);
        }

        // GET: DisciplineSemesters/Create
        public ActionResult Create(int id)
        {
          
        ViewBag.PlanId = id;
            ViewBag.DisciplineName = new SelectList(db.Subjects.Where(d=>!DiplomaDisciplines.Contains(d.Name)), "Id", "Name");
            return View();
        }

        // POST: DisciplineSemesters/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PlanId,SubjectId,IsWithCommission,MemberAmount," +
            "SemesterNumber,Control,CourseType,Lectures," +
            "Labs,Practices,Seminars,Independents,Ksr")] Discipline discipline)
        {
            if (ModelState.IsValid)
            {
            
                db.Disciplines.Add(discipline);
                if (discipline.SubjectId  == 1 && discipline.IsWithCommission) {
                    for (int i = 2; i <= 6; i++) {
                        db.Disciplines.Add(new Discipline { SubjectId = i, PlanId = discipline.PlanId, SemesterNumber = discipline.SemesterNumber });
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Details", "Plan", new { id = discipline.PlanId });
            }
            //прокинуть на страницу ошибки           
            return RedirectToAction("Index", "Exception",new {message= "Неверно заполнена форма" });

        }

        // GET: DisciplineSemesters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discipline discipline = db.Disciplines.Find(id);
            if (discipline == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlanId = id;
            ViewBag.DisciplineName = new SelectList(db.Subjects.Where(d => !DiplomaDisciplines.Contains(d.Name)), "Id", "Name");
            return View();
        }

        // POST: DisciplineSemesters/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SubjectId,Number,Control,CourseType,Lectures,Labs,Practices,Seminars,Independents,Ksr")] Discipline discipline)
        {
            if (ModelState.IsValid)
            {
                db.Entry(discipline).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Plan", new { id = discipline.PlanId });
            }

            return RedirectToAction("Index", "Exception", new { message = "Неверно заполнена форма" });
           
        }

        // GET: DisciplineSemesters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discipline disciplineSemester = db.Disciplines.Find(id);
            if (disciplineSemester == null)
            {
                return HttpNotFound();
            }
            return View(disciplineSemester);
        }

        // POST: DisciplineSemesters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Discipline disciplineSemester = db.Disciplines.Find(id);
            db.Disciplines.Remove(disciplineSemester);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DepartmentWebApplication;
using DataAccessLayer.Entities;
using DepartmentWebApplication.Models;
using System.Reflection;
using DataAccessLayer;

namespace DepartmentWebApplication.Controllers
{
    public class PlanController : Controller
    {
        DataBaseDepartment db = new DataBaseDepartment();
        // GET: Plan
        public ActionResult Index()
        {
            return View(db.Plans.GetAll());
        }

        // GET: Plan/details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.GetItem((int)id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // POST: Plan/details/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int id, params int[] semesters)
        {
            using (var db = new DepartmentEntities())
            {
                List<Semester> list = db.Semesters.Where(s => s.PlanId == id).ToList();
                db.Semesters.RemoveRange(list);

                for (int i = 0; i < semesters.Length; i++)
                {
                    db.Semesters.Add(new Semester()
                    {
                        Number = i + 1,
                        Duration = semesters[i],
                        PlanId = id
                    });
                }
                db.SaveChanges();
            }
            return Redirect("/Plan/Details/" + id);
        }


        // GET: Plan/Create
        public ActionResult Create()
        {
            Plan plan = new Plan();
            plan.Date = DateTime.Now;
            return View(plan);
        }



        //// POST: Plan/Create
        //// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        //// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //// [ValidateAntiForgeryToken]
        //public ActionResult Create(Models.Plan plan)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Plans.Add(mapper.mapFromModel(plan));
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(plan);
        //}


        // POST: Plan/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Speciality,Speciality.Name,Speciality.NameAbbreviated,Specialization,Cipher,Duration,Date,RegNumber,Stage,FormStudy,Budget")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                int specialityId = db.Specialities.GetAll().Find(e => e.Cipher == plan.Speciality.Cipher)?.Id ?? -1;
                if (specialityId == -1)
                {
                    specialityId = db.Specialities.AddGetId(plan.Speciality);
                }

                plan.Speciality = null; // убирает второе добавление специальности в бд
                plan.SpecialityId = specialityId;
                db.Plans.Add(plan);
                return RedirectToAction("Index");
            }

            return View(plan);
        }

        // GET: Plan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.GetItem((int)id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            ViewData["SpecialityId"] = new SelectList(db.Specialities.GetAll(), "Id", "Name", plan.SpecialityId);
            return View(plan);
        }

        // POST: Plan/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SpecialityId,Specialization,Duration,Date,RegNumber,Stage,FormStudy,Budget")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                db.Plans.Edit(plan.Id, plan);
                //  db.Entry(mapper.Convert(planModel)).State = EntityState.Modified;
                //  db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(plan);
        }

        // GET: Plan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.GetItem((int)id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        // POST: Plan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Plans.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Controllers/PracticesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer;
using DataAccessLayer.Entities;

namespace DepartmentWebApplication.Controllers
{
    public class PracticesController : Controller
    {
        private DepartmentEntities db = new DepartmentEntities();

        // GET: Practices
        public ActionResult Index()
        {
            var practices = db.Practices.Include(p => p.Plan);
            return View(practices.ToList());
        }

        // GET: Practices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Practice practice = db.Practices.Find(id);
            if (practice == null)
            {
                return HttpNotFound();
            }
            return View(practice);
        }

        // GET: Practices/Create
        public ActionResult Create(int id)
        {
            ViewBag.PlanId = id;
            return View();
        }

        // POST: Practices/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PracticeType,Course,Duration,PlanId")] Practice practice)
        {
            if (ModelState.IsValid)
            {
                db.Practices.Add(practice);
                db.SaveChanges();
                return RedirectToAction("Details", "Plan", new { id = practice.PlanId });
            }
            return View(practice);
        }

        // GET: Practices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Practice practice = db.Practices.Find(id);
            if (practice == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlanId = new SelectList(db.Plans, "Id", "Specialization", practice.PlanId);
            return View(practice);
        }

        // POST: Practices/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PracticeType,Course,Duration,PlanId")] Practice practice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(practice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlanId = new SelectList(db.Plans, "Id", "Specialization", practice.PlanId);
            return View(practice);
        }

        // GET: Practices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Practice practice = db.Practices.Find(id);
            if (practice == null)
            {
                return HttpNotFound();
            }
            return View(practice);
        }

        // POST: Practices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Practice practice = db.Practices.Find(id);
            db.Practices.Remove(practice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Plan/Create.cshtml
@model DataAccessLayer.Entities.Plan

@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/Styles/MainStyles/form.css")">
}

@section Content{
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "custom-form" }))
    {
        @Html.AntiForgeryToken()
        <div>
            <h4 class="custom-form__title">Создание Учебного плана</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "custom-form__text-danger" })

            <div class="group">
                @Html.LabelFor(model => model.Speciality.Name, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.Speciality.Name, new
                    {
                        htmlAttributes = new
                        {
                            @class = "custom-form__input",
                   @onchange = "WriteAbbreviation(Speciality_NameAbbreviated, this.value)"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.Speciality.Name, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.Speciality.NameAbbreviated, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.Speciality.NameAbbreviated, new { htmlAttributes = new { @class = "custom-form__input" } })
                    @Html.ValidationMessageFor(model => model.Speciality.NameAbbreviated, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.Specialization, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.Specialization, new { htmlAttributes = new { @class = "custom-form__input" } })
                    @Html.ValidationMessageFor(model => model.Specialization, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.Speciality.Cipher, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.Speciality.Cipher, new { htmlAttributes = new { @class = "custom-form__input" } })
                    @Html.ValidationMessageFor(model => model.Speciality.Cipher, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "custom-form__input" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.Date, "{0:yyyy-MM-dd}", new
                    {
                        htmlAttributes = new
                        {
                            @class = "custom-form__input",
                            @type = "date",
                            @Value = Model.Date.ToString("yyyy-MM-dd")
                        }
                    })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.RegNumber, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EditorFor(model => model.RegNumber, new { htmlAttributes = new { @class = "custom-form__input" } })
                    @Html.ValidationMessageFor(model => model.RegNumber, "", new { @class = "custom-form__text-danger" })
                </div>

            </div>
            <div class="group">
                @Html.LabelFor(model => model.Stage, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EnumDropDownListFor(model => model.Stage, htmlAttributes: new { @class = "custom-form__input" })
                    @Html.ValidationMessageFor(model => model.Stage, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.FormStudy, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EnumDropDownListFor(model => model.FormStudy, htmlAttributes: new { @class = "custom-form__input" })
                    @Html.ValidationMessageFor(model => model.FormStudy, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>
            <div class="group">
                @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "custom-form__label" })
                <div>
                    @Html.EnumDropDownListFor(model => model.Budget, htmlAttributes: new { @class = "custom-form__input" })
                    @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "custom-form__text-danger" })
                </div>
            </div>

            <input type="submit" value="Добавить план" class="custom-btn" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "custom-btn" })
        </div>

    }
}

DepartmentWebApplication/DepartmentWebApplication/DepartmentWebApplication/Views/Plan/Details.cshtml
@model DataAccessLayer.Entities.Plan
@using DepartmentWebApplication.Extensions;
@using DataAccessLayer.Enums;


@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/Styles/Plan/main.css")">
    <link rel="stylesheet" href="@Url.Content("~/Styles/Plan/semester-form.css")">
    <link rel="stylesheet" href="@Url.Content("~/Styles/Discipline/discipline-add-form.css")">
}


@section Content{
    <div class="plan-wrapper">
        <header class="plan-header">
            <div class="plan-header__info">
                <p>@Html.DisplayFor(model => model.Date)</p>
                <p>рег. номер @Html.DisplayFor(model => model.RegNumber)</p>
            </div>
            <div class="plan-header__info">
                <h1>Учебный план</h1>
                <p>Специальность @Html.DisplayFor(model => model.Speciality.Name)</p>
                <p>Специализация @Html.DisplayFor(model => model.Specialization)</p>
                <p>Форма получения образования  @Model.FormStudy.GetDisplayName()</p>

            </div>
            <div class="plan-header__info">
                <p>@Model.Stage.GetDisplayName()</p>
                <p>Срок обучения @Html.DisplayFor(model => model.Duration) года</p>
            </div>
        </header>

        @using (Html.BeginForm("Details", "Plan", FormMethod.Post, new { @class = "semester-form" }))
        {
            @Html.AntiForgeryToken();
            if (Model.Semesters.Count == 0)
            {
                for (int i = 0; i < 8; i++)
                {
                    <div class="semester">
                        <span>@(@i + 1) семестр</span>
                        <input name="semesters" type="number" value="17"> <span>недель</span>
                        <label onclick="deleteSemester(this)">-</label>
                    </div>
                }
            }
            else
            {
                foreach (var semester in Model.Semesters)
                {
                    <div class="semester">
                        <span>@semester.Number семестр</span>
                        <input name="semesters" type="number" value="@semester.Duration"> <span>недель</span>
                        <label onclick="deleteSemester(this)">-</label>
                    </div>
                }
            }

            <label id="add" onclick="addSemesterToEnd()">+</label>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Сохранить" class="btn btn-default" onclick="setSelected()" />
                </div>
            </div>
        }
        <section>

            <table class="plan-table">
                <tr class="plan-table__row">
                    <th class="plan-table__head-item">№</th>
                    <th class="plan-table__head-item">Название дисциплины</th>
                    <th class="plan-table__head-item item_rotated">Семестр</th>
                    <th class="plan-table__head-item item_rotated">Вид контроля</th>
                    <th class="plan-table__head-item item_rotated">Тип курсовой</th>
                    <th class="plan-table__head-item item_rotated">Лекции</th>
                    <th class="plan-table__head-item item_rotated">Лабораторные</th>
                    <th class="plan-table__head-item item_rotated">Практические</th>
                    <th class="plan-table__head-item item_rotated">Семинарские</th>
                    <th class="plan-table__head-item item_rotated">Аудиторные</th>
                    <th class="plan-table__head-item item_rotated">Самостоятельная работа</th>
                    <th class="plan-table__head-item item_rotated">КСР</th>
                    <th class="plan-table__head-item item_rotated">Всего</th>
                </tr>

                @{int sequentialNumber = 0;}
                @foreach (var discipline in Model.Disciplines)
                {
                    <tr class="plan-table__row">
                        <td class="plan-table__item">@(++sequentialNumber)</td>
                        <td class="plan-table__item">@discipline.Subject.Name (@discipline.Subject.NameAbbreviated)</td>
                        <td class="plan-table__item">@discipline.SemesterNumber</td>
                        @if (discipline.Control == null)
                        {
                            <td class="plan-table__item">-</td>
                        }
                        else
                        {
                            if (discipline.Control == DataAccessLayer.Enums.Control.Credit)
                            {
                                <td class="plan-table__item">Зачет</td>
                            }
                            else
                            {
                                <td class="plan-table__item">Экзамен</td>
                            }
                        }


                        @if (discipline.CourseType == null)
                        {
                            <td class="plan-table__item">-</td>
                        }
                        else
                        {
                            if (discipline.CourseType == CourseType.Project)
                            {
                                <td class="plan-table__item">Проект</td>
                            }
                            else
                            {
                                <td class="plan-table__item">Работа</td>
                            }
                        }

                        <td class="plan-table__item">@discipline.Lectures</td>
                        <td class="plan-table__item">@discipline.Labs</td>
                        <td class="plan-table__item">@discipline.Practices</td>
                        <td class="plan-table__item">@discipline.Seminars</td>
                        <td class="plan-table__item">@discipline.Audits</td>
                        <td class="plan-table__item">@discipline.Independents</td>
                        <td class="plan-table__item">@discipline.Ksr</td>
                        <td class="plan-table__item">@discipline.All</td>
                    </tr>
                }

                @*Добавление дисциплины с этой же страницы
                    <tr>
                        <td>
                            <input type="number">
                        </td>
                    </tr>*@
            </table>


            <table class="plan-table">

                <tr class="plan-table__row">
                    <th class="plan-table__head-item">
                        Курс
                    </th>
                    <th class="plan-table__head-item">
                        Тип практики
                    </th>
                    <th class="plan-table__head-item">
                        Длительность (недель)
                    </th>
                    <th class="plan-table__head-item"></th>
                </tr>

                @foreach (var practice in Model.Practices)

                {
                    <tr class="plan-table__row">
                        <td class="plan-table__item">@practice.Course</td>
                        @if (practice.PracticeType == PracticeType.Educational)
                        {
                            <td class="plan-table__item">Учебная</td>
                        }
                        else
                        {
                            <td class="plan-table__item">Производственная</td>
                        }
                        <td class="plan-table__item">@practice.Duration</td>
                        <td class="plan-table__item">
                            @Html.ActionLink("Редактировать", "Edit", "Practices", new { id = practice.Id }, new { htmlAttributes = "" })
                            @Html.ActionLink("Удалить", "Delete", "Practices", new { id = practice.Id }, new { htmlAttributes = "" })
                        </td>
                    </tr>
                }


            </table>

            @Html.ActionLink("Добавить дисциплину в план", "Create", "Disciplines", new { id = Model.Id }, new { htmlAttributes = "" })
            @Html.ActionLink("Добавить практику в план", "Create", "Practices", new { id = Model.Id }, new { htmlAttributes = "" })

        </section>


        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id })|
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>

    <script src="~/Scripts/semster-form-script.js"></script>
}